package main

import (
	"fmt"
	"regexp"
	"strings"
)

// Everything this program writes to GitHub is rendered here, by a pure
// function, from data the pipeline already has. None of it is generated by the
// model as free markdown.
//
// That is worth the extra code: the tables always have the columns the reader
// expects, a verification line can never say "✅" for a run that did not
// happen, and every one of these functions is testable without a network or a
// model.

const marker = "<!-- cleaner -->"

// conventionalSubject is the shape a commit subject has to have before this
// program will use the model's version of it.
var conventionalSubject = regexp.MustCompile(`^(fix|feat|refactor|perf|docs|test|chore|build|ci|style)(\([a-zA-Z0-9._/-]+\))?!?: .{3,}$`)

// CommitMessage builds the commit. The subject the implementation phase
// proposed is used when it is well formed, and silently replaced when it is
// not — validating a model's string is cheaper than trusting it, and a
// malformed subject would otherwise reach the repository history forever.
func CommitMessage(class Classification, proposed, fallbackSummary string, ref IssueRef, body string) string {
	subject := strings.TrimSpace(proposed)
	if !conventionalSubject.MatchString(subject) {
		summary := strings.TrimSpace(fallbackSummary)
		summary = strings.TrimSuffix(summary, ".")
		if summary == "" {
			summary = fmt.Sprintf("address issue #%d", ref.Number)
		}
		subject = fmt.Sprintf("%s: %s", class.CommitType(), lowerFirst(summary))
	}
	if len(subject) > 72 {
		subject = strings.TrimSpace(subject[:72])
	}

	var b strings.Builder
	b.WriteString(subject)
	b.WriteString("\n\n")
	if t := strings.TrimSpace(body); t != "" {
		b.WriteString(t)
		b.WriteString("\n\n")
	}
	// The closing keyword lives in the commit body so it works on both landing
	// paths: a squash-merged commit on the default branch closes the issue by
	// itself, and a pull request inherits the keyword from its commits.
	fmt.Fprintf(&b, "Fixes %s\n", ref.URL())
	return b.String()
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	// Only lowercase a plain capitalized word: "Session" is prose, "HTTP" and
	// "REQ-TOOL-04" are names, and mangling those makes the subject wrong.
	r := []rune(s)
	if len(r) > 1 && r[1] >= 'a' && r[1] <= 'z' && r[0] >= 'A' && r[0] <= 'Z' {
		r[0] = r[0] - 'A' + 'a'
	}
	return string(r)
}

// AnalysisComment is posted before any code is written: it is the audit trail
// that says what this run believes and what it is about to do.
func AnalysisComment(a Analysis, branch string, base VerifyResult) string {
	var b strings.Builder
	b.WriteString(marker + "\n## Analysis\n\n")
	b.WriteString("> Posted automatically by `cleaner` before implementing anything.\n\n")

	fmt.Fprintf(&b, "**Classification:** %s  \n**Confidence:** %s  \n**Branch:** `%s`\n\n",
		a.Classification, a.Confidence, branch)

	b.WriteString("### Diagnosis\n\n" + strings.TrimSpace(a.RootCause) + "\n\n")
	b.WriteString("### Planned fix\n\n" + strings.TrimSpace(a.Approach) + "\n\n")

	if len(a.Files) > 0 {
		b.WriteString("**Files to modify**\n\n")
		b.WriteString(fileTable(a.Files))
		b.WriteString("\n")
	}
	if len(a.Assumptions) > 0 {
		b.WriteString("**Assumptions**\n\n")
		for _, s := range a.Assumptions {
			fmt.Fprintf(&b, "- %s\n", s)
		}
		b.WriteString("\n")
	}
	if base.Command != "" {
		fmt.Fprintf(&b, "**Baseline** — `%s`: %s\n\n", base.Command, base.Status())
	}
	b.WriteString("---\n*Implementation follows. The result is posted to this issue whether it succeeds or not.*\n")
	return b.String()
}

// ClarificationComment is the one case where the run stops before touching
// anything, and it is posted as a question rather than as a claim.
func ClarificationComment(c Clarification) string {
	return fmt.Sprintf(`%s
## Clarification needed

`+"`cleaner`"+` stopped before making any changes: this issue has two readings that lead to different fixes, and the codebase does not choose between them.

**Question:** %s

- **A.** %s
- **B.** %s

Answer in a comment and re-run, and the run will proceed on that reading.
`, marker, strings.TrimSpace(c.Question), strings.TrimSpace(c.OptionA), strings.TrimSpace(c.OptionB))
}

// SummaryComment reports the finished run. It takes the VerifyResult rather
// than a boolean so it cannot claim more than was measured.
func SummaryComment(imp Implementation, class Classification, branch, prURL string, base, after VerifyResult, changed []string) string {
	var b strings.Builder
	b.WriteString(marker + "\n## Fix implemented\n\n")
	b.WriteString(strings.TrimSpace(imp.Summary) + "\n\n")

	if len(imp.Changes) > 0 {
		b.WriteString("### Changes\n\n" + fileTable(imp.Changes) + "\n")
	}
	if len(imp.Tests) > 0 {
		b.WriteString("### Tests\n\n")
		for _, t := range imp.Tests {
			fmt.Fprintf(&b, "- `%s` — %s\n", t.Path, t.Covers)
		}
		b.WriteString("\n")
	}

	b.WriteString("### Verification\n\n")
	b.WriteString(verificationLines(base, after, changed))
	b.WriteString("\n")

	if len(imp.Limitations) > 0 {
		b.WriteString("### Not covered\n\n")
		for _, s := range imp.Limitations {
			fmt.Fprintf(&b, "- %s\n", s)
		}
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "**Branch:** `%s`", branch)
	if prURL != "" {
		fmt.Fprintf(&b, "  \n**Pull request:** %s", prURL)
	}
	b.WriteString("\n\n---\n*Posted by `cleaner`. A human still has to review it.*\n")
	return b.String()
}

// FailureComment is what makes this program safe to leave running: a run that
// could not finish says so on the issue, in the same place a successful one
// would have, instead of dying in a terminal nobody is watching.
func FailureComment(stage string, cause error, branch string, after VerifyResult) string {
	var b strings.Builder
	b.WriteString(marker + "\n## Automated fix attempt failed\n\n")
	fmt.Fprintf(&b, "`cleaner` stopped during **%s**:\n\n```\n%s\n```\n\n", stage, strings.TrimSpace(cause.Error()))
	if branch != "" {
		fmt.Fprintf(&b, "Whatever was written is on the local branch `%s` — nothing was merged and nothing was pushed by this run.\n\n", branch)
	}
	if after.Command != "" && !after.Skipped {
		fmt.Fprintf(&b, "Last `%s` run: %s\n\n```\n%s\n```\n\n", after.Command, after.Status(), after.Output)
	}
	b.WriteString("---\n*Posted by `cleaner`. This issue still needs a human.*\n")
	return b.String()
}

// PullRequestBody reuses the summary and adds the closing keyword.
func PullRequestBody(imp Implementation, ref IssueRef, base, after VerifyResult, changed []string) string {
	var b strings.Builder
	b.WriteString("## Summary\n\n" + strings.TrimSpace(imp.Summary) + "\n\n")
	fmt.Fprintf(&b, "Closes #%d\n\n", ref.Number)

	if len(imp.Changes) > 0 {
		b.WriteString("## Changes\n\n" + fileTable(imp.Changes) + "\n")
	}
	if len(imp.Tests) > 0 {
		b.WriteString("## Tests\n\n")
		for _, t := range imp.Tests {
			fmt.Fprintf(&b, "- `%s` — %s\n", t.Path, t.Covers)
		}
		b.WriteString("\n")
	}
	b.WriteString("## Verification\n\n" + verificationLines(base, after, changed) + "\n")
	if len(imp.Limitations) > 0 {
		b.WriteString("## Not covered\n\n")
		for _, s := range imp.Limitations {
			fmt.Fprintf(&b, "- %s\n", s)
		}
		b.WriteString("\n")
	}
	b.WriteString("---\n*Opened by `cleaner`, an autonomous issue fixer. Review it like any other pull request.*\n")
	return b.String()
}

// verificationLines is the honest version of af-fix's four-line checklist of
// green ticks. Each line reports something that was actually measured, and
// "no verification command" is stated rather than omitted.
func verificationLines(base, after VerifyResult, changed []string) string {
	var b strings.Builder
	switch {
	case after.Skipped || after.Command == "":
		b.WriteString("- ⚠️ No verification command was detected for this project — **the change is unverified**.\n")
	case after.OK && base.OK:
		fmt.Fprintf(&b, "- ✅ `%s` passes (it also passed before the change).\n", after.Command)
	case after.OK && !base.OK && !base.Skipped:
		fmt.Fprintf(&b, "- ✅ `%s` passes now; it was **already failing** before this change.\n", after.Command)
	case after.OK:
		fmt.Fprintf(&b, "- ✅ `%s` passes.\n", after.Command)
	default:
		fmt.Fprintf(&b, "- ❌ `%s` fails (exit %d).\n", after.Command, after.ExitCode)
	}
	fmt.Fprintf(&b, "- %d file(s) changed: %s\n", len(changed), codeList(changed))
	return b.String()
}

func fileTable(changes []FileChange) string {
	var b strings.Builder
	b.WriteString("| File | Change |\n|---|---|\n")
	for _, c := range changes {
		fmt.Fprintf(&b, "| `%s` | %s |\n", c.Path, escapePipes(c.Change))
	}
	return b.String()
}

// escapePipes keeps a description containing `|` from breaking the table it
// is rendered into.
func escapePipes(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "\n", " "), "|", `\|`)
}

func codeList(items []string) string {
	if len(items) == 0 {
		return "none"
	}
	const max = 12
	out := make([]string, 0, len(items))
	for i, s := range items {
		if i == max {
			out = append(out, fmt.Sprintf("and %d more", len(items)-max))
			break
		}
		out = append(out, "`"+s+"`")
	}
	return strings.Join(out, ", ")
}
